name: Main
on:
  pull_request:

jobs:
  scout:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2.5.0

      - name: Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ybdc23/dc23hello
          labels: org.opencontainers.image.revision=${{ env.SHA }}
          tags: latest

      - name: Docker Build
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: false
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Check Image
        uses: docker/scout-action@main
        with:
          command: quickview,cves
          image: local://${{ steps.meta.outputs.tags }}

      - name: Compare
        uses: docker/scout-action@main
        with:
          command: compare
          image: local://${{ steps.meta.outputs.tags }}
          to: registry://${{ steps.meta.outputs.tags }}

